from __future__ import annotations

"""
IMU2CLIP integration findings, verified against the public Meta AI repository
and arXiv paper on 2026-04-29:

- Repository: https://github.com/facebookresearch/imu2clip is public, archived,
  and contains code/configs but no GitHub releases or package artifacts.
- Public pretrained IMU encoder weights were not found. A later UniMTS paper
  explicitly states that IMU2CLIP pretrained weights were not released, so this
  module supports loading private/reproduced checkpoints and documents Option B.
- Official contrastive config uses `imu_encoder_name: "mw2"`, `window_sec: 2.5`,
  `target_fps: 10`, and `imu_sampling_rate: 200` for Ego4D.
- The IMU encoder branch used by the repo is `MW2StackRNNPooling`: GroupNorm over
  6 channels, three Conv1d+MaxPool blocks, GroupNorm over CNN channels, then a GRU.
- Input format is channels-first `(B, 6, T)`. Ego4D preprocessing resamples IMU
  to 200 Hz and returns `signal.T`, i.e. six channels by timesteps.
- The encoder output is the final GRU hidden state shaped `(B, 512)` when
  `final_embedding_size` is 512. Video/text encoders are separate CLIP branches
  and are intentionally not loaded here.

Key worktree differences from TS2Vec:
- Architecture: TS2Vec uses dilated temporal CNNs; IMU2CLIP uses CNN + GRU.
- Pretraining: TS2Vec was trained from scratch here; IMU2CLIP expects Ego4D
  cross-modal pretraining, or Option B below when public weights are unavailable.
- Loss: TS2Vec hierarchical contrastive; IMU2CLIP cross-modal contrastive, or
  SimCLR-style IMU-only contrastive for Option B.
- Embedding dim: TS2Vec worktree used 320; IMU2CLIP uses 512.
- Normalization: TS2Vec uses its training normalization; IMU2CLIP uses per-clip,
  per-channel normalization to match the public Ego4D IMU path.
- Windowing: TS2Vec is variable length; IMU2CLIP expects short fixed windows.
- Domain match: TS2Vec is generic time-series; IMU2CLIP targets egocentric
  head-mounted IMU.

Option B note:
Since official pretrained weights are not publicly available, the architecture
builder in this file can construct a structurally equivalent MW2 CNN+GRU encoder
for checkpoints trained with an IMU-only SimCLR-style objective. Such weights are
not generated by this module; use Modal training infrastructure for that step.
"""

from collections import OrderedDict
from pathlib import Path
from typing import Any, Mapping, Sequence

import numpy as np


DEFAULT_IMU2CLIP_EXPECTED_HZ = 200
DEFAULT_IMU2CLIP_OUTPUT_DIM = 512


def _optional_torch_module_base():
    try:
        import torch

        return torch.nn.Module
    except Exception:
        return object


class IMU2CLIPEncoder:
    """Wraps the IMU2CLIP IMU encoder branch for long raw IMU clips."""

    def __init__(
        self,
        checkpoint_path: str,
        device: str = "cpu",
        target_hz: int = 30,
        window_len_s: float = 2.0,
        stride_ratio: float = 0.5,
        pool: str = "max",
        expected_hz: int = DEFAULT_IMU2CLIP_EXPECTED_HZ,
        batch_size: int = 128,
        model_window_timesteps: int = 1000,
    ):
        self.checkpoint_path = str(checkpoint_path)
        self.device = str(device)
        self.target_hz = int(target_hz)
        self.expected_hz = int(expected_hz)
        self.window_len_s = float(window_len_s)
        self.stride_ratio = float(stride_ratio)
        self.pool = str(pool)
        self.batch_size = int(batch_size)
        self.model_window_timesteps = int(model_window_timesteps)
        self.model, self.architecture = self._load_model(self.checkpoint_path)

    def encode_clip(self, clip: np.ndarray) -> np.ndarray:
        prepared = self._prepare_clip(clip, window_len_s=self.window_len_s)
        windows = self._window_clip(
            prepared,
            window_timesteps=max(1, int(round(self.window_len_s * self.expected_hz))),
            stride_timesteps=max(1, int(round(self.window_len_s * self.expected_hz * self.stride_ratio))),
        )
        return self._embed_windows(windows, pool=self.pool)

    def encode_clip_multiscale(
        self,
        clip: np.ndarray,
        window_sizes_s: list[float] | None = None,
        stride_ratio: float = 0.5,
        pool: str = "max",
        combine: str = "concat",
    ) -> np.ndarray:
        """
        Embed a long clip at several fixed window sizes.

        The official model was trained around short Ego4D windows. Larger 5s and
        10s windows are out-of-distribution, but can still expose useful geometry
        for novelty scoring, so they are opt-in and reported distinctly.
        """

        sizes = [2.0, 5.0, 10.0] if window_sizes_s is None else [float(v) for v in window_sizes_s]
        embeddings = []
        old_stride = self.stride_ratio
        try:
            self.stride_ratio = float(stride_ratio)
            for window_s in sizes:
                prepared = self._prepare_clip(clip, window_len_s=window_s)
                windows = self._window_clip(
                    prepared,
                    window_timesteps=max(1, int(round(window_s * self.expected_hz))),
                    stride_timesteps=max(1, int(round(window_s * self.expected_hz * self.stride_ratio))),
                )
                embeddings.append(self._embed_windows(windows, pool=pool))
        finally:
            self.stride_ratio = old_stride

        if combine == "concat":
            return _l2_normalize(np.concatenate(embeddings).astype("float32"))
        if combine == "mean":
            return _l2_normalize(np.mean(np.vstack(embeddings), axis=0).astype("float32"))
        raise ValueError("combine must be 'concat' or 'mean'.")

    def _prepare_clip(self, clip: np.ndarray, *, window_len_s: float) -> np.ndarray:
        del window_len_s
        values = _finite_imu_clip(clip)
        resampled = self._resample(values, original_hz=self.target_hz, target_hz=self.expected_hz)
        return self._normalize_clip(resampled)

    def _normalize_clip(self, clip: np.ndarray) -> np.ndarray:
        values = _finite_imu_clip(clip)
        mean = np.mean(values, axis=0, keepdims=True)
        std = np.std(values, axis=0, keepdims=True)
        std = np.where(std < 1.0e-6, 1.0, std)
        return ((values - mean) / std).astype("float32")

    def _resample(self, clip: np.ndarray, original_hz: int, target_hz: int) -> np.ndarray:
        values = _finite_imu_clip(clip)
        if int(original_hz) == int(target_hz):
            return values.astype("float32")
        target_len = max(1, int(round(len(values) * float(target_hz) / float(original_hz))))
        try:
            from scipy.signal import resample

            return np.asarray(resample(values, target_len, axis=0), dtype="float32")
        except Exception:
            old_x = np.linspace(0.0, 1.0, num=len(values), endpoint=True)
            new_x = np.linspace(0.0, 1.0, num=target_len, endpoint=True)
            columns = [np.interp(new_x, old_x, values[:, channel]) for channel in range(values.shape[1])]
            return np.stack(columns, axis=1).astype("float32")

    def _window_clip(
        self,
        clip: np.ndarray,
        window_timesteps: int,
        stride_timesteps: int,
    ) -> np.ndarray:
        values = _finite_imu_clip(clip)
        window = int(window_timesteps)
        stride = int(stride_timesteps)
        if window <= 0 or stride <= 0:
            raise ValueError("window_timesteps and stride_timesteps must be positive.")
        if len(values) < window:
            return np.empty((0, window, values.shape[1]), dtype="float32")
        starts = range(0, len(values) - window + 1, stride)
        return np.stack([values[start : start + window] for start in starts]).astype("float32")

    def _embed_windows(self, windows: np.ndarray, *, pool: str) -> np.ndarray:
        if windows.ndim != 3 or windows.shape[2] != 6:
            raise ValueError("windows must be shaped (N, T, 6).")
        if len(windows) == 0:
            raise ValueError("clip is shorter than the requested IMU2CLIP window.")
        window_embeddings = self._forward_windows(windows)
        if pool == "max":
            pooled = np.max(window_embeddings, axis=0)
        elif pool == "mean":
            pooled = np.mean(window_embeddings, axis=0)
        else:
            raise ValueError("pool must be 'max' or 'mean'.")
        return _l2_normalize(pooled.astype("float32"))

    def _forward_windows(self, windows: np.ndarray) -> np.ndarray:
        torch = _require_torch()
        outputs = []
        self.model.eval()
        with torch.inference_mode():
            for start in range(0, len(windows), self.batch_size):
                batch = self._resize_windows_for_model(windows[start : start + self.batch_size]).transpose(0, 2, 1)
                tensor = torch.as_tensor(batch, dtype=torch.float32, device=self.device)
                output = self.model(tensor)
                outputs.append(output.detach().cpu().numpy())
        return np.vstack(outputs).astype("float32")

    def _resize_windows_for_model(self, windows: np.ndarray) -> np.ndarray:
        target = max(1, int(self.model_window_timesteps))
        values = np.asarray(windows, dtype=np.float32)
        if values.shape[1] == target:
            return values
        old_x = np.linspace(0.0, 1.0, num=values.shape[1], endpoint=True)
        new_x = np.linspace(0.0, 1.0, num=target, endpoint=True)
        output = np.empty((values.shape[0], target, values.shape[2]), dtype=np.float32)
        for row in range(values.shape[0]):
            for channel in range(values.shape[2]):
                output[row, :, channel] = np.interp(new_x, old_x, values[row, :, channel])
        return output

    def _load_model(self, checkpoint_path: str):
        torch = _require_torch()
        payload = torch.load(str(checkpoint_path), map_location=self.device)
        encoder_config = _extract_encoder_config(payload)
        state_dict = _extract_state_dict(payload)
        state_dict = _strip_state_dict_prefixes(state_dict)
        architecture = self._infer_architecture_from_checkpoint(state_dict)
        if _is_option_b_style_checkpoint(state_dict, encoder_config):
            model = IMU2CLIPStyleEncoder(
                in_channels=int(architecture["in_channels"]),
                hidden_dim=int(architecture["gru_hidden_size"]),
                output_dim=int(architecture["output_dim"]),
                gru_layers=int(architecture["gru_layers"]),
                cnn_layers=int(architecture["cnn_layers"]),
                cnn_channels=int(architecture["cnn_channels"][0]),
            )
        else:
            model = _build_mw2_stack_rnn_pooling(
                input_dim=int(architecture["cnn_channels"][0]),
                size_embeddings=int(architecture["gru_hidden_size"]),
            )
        missing, unexpected = model.load_state_dict(state_dict, strict=False)
        allowed_missing = set()
        if set(missing) - allowed_missing:
            raise ValueError(f"Checkpoint is missing IMU2CLIP encoder keys: {sorted(missing)}")
        if unexpected:
            raise ValueError(f"Checkpoint has unexpected IMU2CLIP encoder keys: {sorted(unexpected)}")
        return model.to(self.device), architecture

    def _infer_architecture_from_checkpoint(self, state_dict: Mapping[str, Any]) -> dict[str, Any]:
        shapes = {str(key): _shape(value) for key, value in state_dict.items()}
        conv_keys = sorted(
            key
            for key, shape in shapes.items()
            if key.endswith(".weight") and len(shape) == 3 and ".net.0.weight" in key
        )
        if not conv_keys:
            raise ValueError("Could not infer IMU2CLIP CNN layers from checkpoint.")
        conv_shapes = [shapes[key] for key in conv_keys]
        gru_key = next((key for key in shapes if key.endswith("weight_hh_l0")), None)
        if gru_key is None:
            raise ValueError("Could not infer IMU2CLIP GRU layer from checkpoint.")
        gru_hidden_size = int(shapes[gru_key][1])
        gru_layers = len([key for key in shapes if key.endswith(".weight_hh_l0") or "weight_hh_l" in key and len(shapes[key]) == 2])
        projection_key = next((key for key in shapes if key.endswith("projection.weight")), None)
        output_dim = int(shapes[projection_key][0]) if projection_key is not None else gru_hidden_size
        return {
            "architecture": "mw2_stack_rnn_pooling",
            "input_format": "B,C,T",
            "in_channels": int(conv_shapes[0][1]),
            "cnn_layers": len(conv_shapes),
            "cnn_channels": [int(shape[0]) for shape in conv_shapes],
            "cnn_kernel_sizes": [int(shape[2]) for shape in conv_shapes],
            "gru_hidden_size": gru_hidden_size,
            "gru_layers": max(1, int(gru_layers)),
            "output_dim": output_dim,
            "expected_hz": DEFAULT_IMU2CLIP_EXPECTED_HZ,
            "model_window_timesteps": 1000,
        }


class IMU2CLIPStyleEncoder(_optional_torch_module_base()):
    """
    Option B encoder: structurally equivalent IMU2CLIP-style CNN+GRU branch.

    This is trained with a SimCLR-style IMU-only contrastive objective when the
    original Ego4D cross-modal IMU2CLIP weights are unavailable. It keeps the
    same channels-first `(B, 6, T)` input convention and emits a 512-d embedding.
    """

    def __init__(
        self,
        in_channels: int = 6,
        hidden_dim: int = 512,
        output_dim: int = 512,
        gru_layers: int = 2,
        cnn_layers: int = 4,
        cnn_channels: int = 32,
    ):
        torch = _require_torch()
        nn = torch.nn
        super().__init__()
        if not hasattr(self, "_modules"):
            raise RuntimeError("IMU2CLIPStyleEncoder must be imported in an environment with torch installed.")
        if in_channels != 6:
            raise ValueError("IMU2CLIPStyleEncoder expects six IMU channels.")
        if cnn_layers < 1:
            raise ValueError("cnn_layers must be positive.")
        if gru_layers < 1:
            raise ValueError("gru_layers must be positive.")

        kernels = [10, 5, 5, 3, 3, 3]
        blocks = []
        current_channels = int(in_channels)
        for layer_idx in range(int(cnn_layers)):
            kernel = kernels[min(layer_idx, len(kernels) - 1)]
            blocks.append((str(layer_idx), _make_conv_pool_block(current_channels, int(cnn_channels), kernel)))
            current_channels = int(cnn_channels)

        self.input_norm = nn.GroupNorm(2, int(in_channels))
        self.blocks = nn.Sequential(OrderedDict(blocks))
        self.temporal_pool = nn.AdaptiveAvgPool1d(int(cnn_channels))
        self.channel_norm = nn.GroupNorm(_largest_group_divisor(int(cnn_channels), preferred=4), int(cnn_channels))
        self.gru = nn.GRU(
            batch_first=True,
            input_size=int(cnn_channels),
            hidden_size=int(hidden_dim),
            num_layers=int(gru_layers),
        )
        self.projection = nn.Identity() if int(output_dim) == int(hidden_dim) else nn.Linear(int(hidden_dim), int(output_dim))

    def forward(self, batch):
        torch = _require_torch()
        functional = torch.nn.functional
        encoded = self.channel_norm(self.temporal_pool(self.blocks(self.input_norm(batch))))
        _, hidden = self.gru(encoded)
        embedding = self.projection(hidden[-1])
        return functional.normalize(embedding, dim=1)


def option_b_checkpoint_metadata() -> dict[str, Any]:
    return {
        "architecture": "imu2clip_style_mw2",
        "training": "SimCLR-style IMU-only contrastive",
        "input_format": "B,C,T",
        "in_channels": 6,
        "output_dim": DEFAULT_IMU2CLIP_OUTPUT_DIM,
        "normalization": "per-clip per-channel",
        "expected_hz": DEFAULT_IMU2CLIP_EXPECTED_HZ,
    }


def imu_augment(clip: np.ndarray, *, rng: np.random.Generator | None = None) -> np.ndarray:
    """Apply one random IMU-only contrastive augmentation for Option B training."""

    random = np.random.default_rng() if rng is None else rng
    values = _finite_imu_clip(clip)
    choice = int(random.integers(0, 5))
    if choice == 0:
        return (values + random.normal(0.0, 0.05, size=values.shape)).astype("float32")
    if choice == 1:
        factor = float(random.uniform(0.8, 1.2))
        target_len = max(2, int(round(len(values) * factor)))
        old_x = np.linspace(0.0, 1.0, len(values))
        new_x = np.linspace(0.0, 1.0, target_len)
        return np.stack([np.interp(new_x, old_x, values[:, col]) for col in range(6)], axis=1).astype("float32")
    if choice == 2:
        output = values.copy()
        output[:, int(random.integers(0, 6))] = 0.0
        return output.astype("float32")
    if choice == 3:
        return (values * float(random.uniform(0.8, 1.2))).astype("float32")
    crop_len = max(2, int(round(len(values) * 0.8)))
    start = int(random.integers(0, max(1, len(values) - crop_len + 1)))
    return values[start : start + crop_len].astype("float32")


def _build_mw2_stack_rnn_pooling(input_dim: int = 32, size_embeddings: int = 512):
    torch = _require_torch()
    nn = torch.nn

    class MW2StackRNNPooling(nn.Module):
        def __init__(self):
            super().__init__()
            self.net = nn.Sequential(
                OrderedDict(
                    [
                        ("0", nn.GroupNorm(2, 6)),
                        ("1", _make_conv_pool_block(6, input_dim, 10)),
                        ("2", _make_conv_pool_block(input_dim, input_dim, 5)),
                        ("3", _make_conv_pool_block(input_dim, input_dim, 5)),
                        ("4", nn.GroupNorm(4, input_dim)),
                        ("5", nn.GRU(batch_first=True, input_size=input_dim, hidden_size=size_embeddings)),
                    ]
                )
            )

        def forward(self, batch):
            encoded = self.net[:5](batch)
            _, hidden = self.net[5](encoded)
            return hidden[0]

    return MW2StackRNNPooling()


def _make_conv_pool_block(in_channels: int, out_channels: int, kernel_size: int):
    torch = _require_torch()
    nn = torch.nn

    class Block(nn.Module):
        def __init__(self):
            super().__init__()
            self.net = nn.Sequential(
                nn.Conv1d(in_channels=in_channels, out_channels=out_channels, kernel_size=kernel_size, dilation=2, bias=False),
                nn.MaxPool1d(kernel_size=3),
            )

        def forward(self, batch):
            return self.net(batch)

    return Block()


def _largest_group_divisor(channels: int, *, preferred: int) -> int:
    for groups in range(min(preferred, channels), 0, -1):
        if channels % groups == 0:
            return groups
    return 1


def _extract_encoder_config(payload: Any) -> Mapping[str, Any]:
    if isinstance(payload, Mapping):
        value = payload.get("encoder_config")
        if isinstance(value, Mapping):
            return value
    return {}


def _is_option_b_style_checkpoint(state_dict: Mapping[str, Any], encoder_config: Mapping[str, Any]) -> bool:
    if encoder_config.get("architecture") == "imu2clip_style_mw2":
        return True
    return any(str(key).startswith(("input_norm.", "blocks.", "temporal_pool.", "channel_norm.", "gru.", "projection.")) for key in state_dict)


def _extract_state_dict(payload: Any) -> Mapping[str, Any]:
    if isinstance(payload, Mapping):
        for key in ("state_dict", "model_state_dict", "encoder_state_dict"):
            value = payload.get(key)
            if isinstance(value, Mapping):
                return value
        return payload
    raise ValueError("Checkpoint must contain a state_dict mapping.")


def _strip_state_dict_prefixes(state_dict: Mapping[str, Any]) -> dict[str, Any]:
    prefixes = ("module.", "imu_encoder.", "encoder.", "model.")
    output: dict[str, Any] = {}
    for key, value in state_dict.items():
        clean = str(key)
        changed = True
        while changed:
            changed = False
            for prefix in prefixes:
                if clean.startswith(prefix):
                    clean = clean[len(prefix) :]
                    changed = True
        output[clean] = value
    return output


def _shape(value: Any) -> tuple[int, ...]:
    shape = getattr(value, "shape", None)
    if shape is None:
        return tuple(np.asarray(value).shape)
    return tuple(int(dim) for dim in shape)


def _finite_imu_clip(clip: np.ndarray) -> np.ndarray:
    values = np.asarray(clip, dtype=np.float32)
    if values.ndim != 2 or values.shape[1] < 6:
        raise ValueError("clip must be shaped (T, 6) or wider.")
    if values.shape[0] == 0:
        raise ValueError("clip must contain at least one timestep.")
    return np.nan_to_num(values[:, :6], nan=0.0, posinf=0.0, neginf=0.0).astype("float32")


def _l2_normalize(vector: np.ndarray) -> np.ndarray:
    values = np.asarray(vector, dtype=np.float32)
    norm = float(np.linalg.norm(values))
    if norm < 1.0e-12:
        return values
    return (values / norm).astype("float32")


def _require_torch():
    try:
        import torch
    except Exception as exc:
        raise RuntimeError("IMU2CLIP inference requires torch; run this path in Modal or an ML environment.") from exc
    return torch
